### PR TITLE
Add abm scenarios

### PR DESCRIPTION
**Pull request by andredaa**
- allow subselection of results by result-properties

### CODE REVIEW

**Comment by luftj** [comment]
where's the abm data? make a mock for the tests pls :)

**Comment by andredaa** [comment]
@luftj : added the test data :)

**Comment by luftj** [comment]
Use-case specific data should not be in the general CityPyO repo. You can put them somewhere else but put a download in a test/setup function

**Comment by andredaa** [comment]
> Use-case specific data should not be in the general CityPyO repo. You can put them somewhere else but put a download in a test/setup function

you are right. I removed the data from the repo and introduced a setup script that downloads the data.

**Pull request closed without merging**
